#!/usr/bin/env bash
# Usage: brett_run_rovioli_live <output save folder> [<additional rovioli flags>]

LOCALIZATION_MAP_OUTPUT=$1
NCAMERA_CALIBRATION="/home/arl/maplab_ws/src/arl_slam/resources/zr300_calibration/ncamera-2018-05-11-15-05-18.yaml"
IMU_PARAMETERS_MAPLAB="/home/arl/maplab_ws/src/arl_slam/resources/zr300_calibration/imu-zr300-maplab.yaml"
IMU_PARAMETERS_ROVIO="/home/arl/maplab_ws/src/arl_slam/resources/zr300_calibration/imu-zr300-rovio.yaml"
REST=$@

rosrun rovioli rovioli \
  --rovio_enable_frame_visualization=false \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --imu_parameters_rovio=$IMU_PARAMETERS_ROVIO \
  --datasource_type="rostopic" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --map_builder_save_image_as_resources=false \
  --optimize_map_to_localization_map=false $REST
  
